Backend: Vitis
ClockPeriod: 10
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision: ap_fixed<32, 15>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
InputShapes:
  input_layer:
  - 100
KerasModel: !keras_model 'my-hls-test/keras_model.keras'
OutputDir: my-hls-test
OutputPredictions: null
OutputShapes:
  layer9_out:
  - 1
Part: xczu7ev-ffvc1156-2-e
ProjectName: myproject
Stamp: deda4ae9
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
