// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module my_prj_accelerator_decision_function_ap_fixed_32_18_5_3_0_ap_fixed_32_18_5_3_0_11 (
        ap_ready,
        x_4_val,
        x_10_val,
        x_11_val,
        x_12_val,
        x_14_val,
        x_16_val,
        x_17_val,
        x_19_val,
        x_21_val,
        x_22_val,
        x_23_val,
        x_24_val,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [31:0] x_4_val;
input  [31:0] x_10_val;
input  [31:0] x_11_val;
input  [31:0] x_12_val;
input  [31:0] x_14_val;
input  [31:0] x_16_val;
input  [31:0] x_17_val;
input  [31:0] x_19_val;
input  [31:0] x_21_val;
input  [31:0] x_22_val;
input  [31:0] x_23_val;
input  [31:0] x_24_val;
output  [9:0] ap_return;
input   ap_rst;

wire   [0:0] icmp_ln4_192_fu_244_p2;
wire   [0:0] icmp_ln4_fu_238_p2;
wire   [0:0] icmp_ln4_193_fu_250_p2;
wire   [0:0] and_ln113_fu_340_p2;
wire   [0:0] icmp_ln4_194_fu_256_p2;
wire   [0:0] and_ln113_181_fu_346_p2;
wire   [0:0] icmp_ln4_195_fu_262_p2;
wire   [0:0] and_ln113_182_fu_352_p2;
wire   [0:0] icmp_ln4_196_fu_268_p2;
wire   [0:0] xor_ln115_fu_364_p2;
wire   [0:0] and_ln113_196_fu_370_p2;
wire   [0:0] xor_ln115_83_fu_382_p2;
wire   [0:0] icmp_ln4_197_fu_274_p2;
wire   [0:0] and_ln115_fu_388_p2;
wire   [0:0] icmp_ln4_198_fu_280_p2;
wire   [0:0] and_ln113_185_fu_394_p2;
wire   [0:0] icmp_ln4_199_fu_286_p2;
wire   [0:0] xor_ln115_84_fu_406_p2;
wire   [0:0] and_ln113_197_fu_412_p2;
wire   [0:0] xor_ln115_85_fu_424_p2;
wire   [0:0] icmp_ln4_200_fu_292_p2;
wire   [0:0] and_ln115_11_fu_430_p2;
wire   [0:0] icmp_ln4_201_fu_298_p2;
wire   [0:0] xor_ln115_86_fu_442_p2;
wire   [0:0] and_ln113_198_fu_448_p2;
wire   [0:0] icmp_ln4_202_fu_304_p2;
wire   [0:0] xor_ln115_87_fu_460_p2;
wire   [0:0] icmp_ln4_203_fu_310_p2;
wire   [0:0] and_ln113_190_fu_466_p2;
wire   [0:0] icmp_ln4_204_fu_316_p2;
wire   [0:0] and_ln113_191_fu_472_p2;
wire   [0:0] icmp_ln4_205_fu_322_p2;
wire   [0:0] and_ln113_192_fu_478_p2;
wire   [0:0] icmp_ln4_206_fu_328_p2;
wire   [0:0] and_ln113_199_fu_496_p2;
wire   [0:0] xor_ln115_88_fu_490_p2;
wire   [0:0] icmp_ln4_207_fu_334_p2;
wire   [0:0] and_ln113_194_fu_502_p2;
wire   [0:0] and_ln113_183_fu_358_p2;
wire   [0:0] xor_ln128_fu_514_p2;
wire   [0:0] and_ln113_184_fu_376_p2;
wire   [1:0] zext_ln128_fu_520_p1;
wire   [0:0] or_ln128_fu_524_p2;
wire   [1:0] select_ln128_fu_530_p3;
wire   [1:0] select_ln128_181_fu_538_p3;
wire   [0:0] and_ln113_186_fu_400_p2;
wire   [2:0] zext_ln128_31_fu_546_p1;
wire   [0:0] or_ln128_137_fu_550_p2;
wire   [2:0] select_ln128_182_fu_556_p3;
wire   [0:0] or_ln128_138_fu_564_p2;
wire   [0:0] and_ln113_187_fu_418_p2;
wire   [2:0] select_ln128_183_fu_570_p3;
wire   [0:0] or_ln128_139_fu_578_p2;
wire   [2:0] select_ln128_184_fu_584_p3;
wire   [2:0] select_ln128_185_fu_592_p3;
wire   [0:0] and_ln113_188_fu_436_p2;
wire   [3:0] zext_ln128_32_fu_600_p1;
wire   [0:0] or_ln128_140_fu_604_p2;
wire   [0:0] and_ln113_189_fu_454_p2;
wire   [3:0] select_ln128_186_fu_610_p3;
wire   [0:0] or_ln128_141_fu_618_p2;
wire   [3:0] select_ln128_187_fu_624_p3;
wire   [0:0] and_ln113_193_fu_484_p2;
wire   [3:0] select_ln128_188_fu_632_p3;
wire   [0:0] or_ln128_142_fu_640_p2;
wire   [3:0] select_ln128_189_fu_646_p3;
wire   [0:0] or_ln128_143_fu_654_p2;
wire   [3:0] select_ln128_190_fu_660_p3;
wire   [0:0] or_ln128_144_fu_668_p2;
wire   [3:0] select_ln128_191_fu_674_p3;
wire   [0:0] or_ln128_145_fu_682_p2;
wire   [0:0] and_ln113_195_fu_508_p2;
wire   [3:0] select_ln128_192_fu_688_p3;
wire   [3:0] select_ln128_193_fu_702_p3;
wire   [0:0] or_ln128_146_fu_696_p2;
wire   [4:0] zext_ln128_33_fu_710_p1;
wire   [0:0] or_ln128_147_fu_714_p2;
wire   [4:0] select_ln128_194_fu_720_p3;
wire   [9:0] agg_result_fu_736_p37;
wire   [4:0] agg_result_fu_736_p38;
wire   [9:0] agg_result_fu_736_p39;
wire   [4:0] agg_result_fu_736_p1;
wire   [4:0] agg_result_fu_736_p3;
wire   [4:0] agg_result_fu_736_p5;
wire   [4:0] agg_result_fu_736_p7;
wire   [4:0] agg_result_fu_736_p9;
wire   [4:0] agg_result_fu_736_p11;
wire   [4:0] agg_result_fu_736_p13;
wire   [4:0] agg_result_fu_736_p15;
wire   [4:0] agg_result_fu_736_p17;
wire   [4:0] agg_result_fu_736_p19;
wire   [4:0] agg_result_fu_736_p21;
wire   [4:0] agg_result_fu_736_p23;
wire   [4:0] agg_result_fu_736_p25;
wire   [4:0] agg_result_fu_736_p27;
wire   [4:0] agg_result_fu_736_p29;
wire   [4:0] agg_result_fu_736_p31;
wire  signed [4:0] agg_result_fu_736_p33;
wire  signed [4:0] agg_result_fu_736_p35;
wire    ap_ce_reg;

(* dissolve_hierarchy = "yes" *) my_prj_accelerator_sparsemux_37_5_10_1_1_x1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 10 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 10 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 10 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 10 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 10 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 10 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 10 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 10 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 10 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 10 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 10 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 10 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 10 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 10 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 10 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 10 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 10 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 10 ),
    .def_WIDTH( 10 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 10 ))
sparsemux_37_5_10_1_1_x1_U248(
    .din0(10'd632),
    .din1(10'd275),
    .din2(10'd724),
    .din3(10'd493),
    .din4(10'd11),
    .din5(10'd1),
    .din6(10'd6),
    .din7(10'd282),
    .din8(10'd180),
    .din9(10'd0),
    .din10(10'd32),
    .din11(10'd2),
    .din12(10'd0),
    .din13(10'd0),
    .din14(10'd25),
    .din15(10'd305),
    .din16(10'd0),
    .din17(10'd0),
    .def(agg_result_fu_736_p37),
    .sel(agg_result_fu_736_p38),
    .dout(agg_result_fu_736_p39)
);

assign and_ln113_181_fu_346_p2 = (icmp_ln4_193_fu_250_p2 & and_ln113_fu_340_p2);

assign and_ln113_182_fu_352_p2 = (icmp_ln4_194_fu_256_p2 & and_ln113_181_fu_346_p2);

assign and_ln113_183_fu_358_p2 = (icmp_ln4_195_fu_262_p2 & and_ln113_182_fu_352_p2);

assign and_ln113_184_fu_376_p2 = (and_ln113_196_fu_370_p2 & and_ln113_181_fu_346_p2);

assign and_ln113_185_fu_394_p2 = (icmp_ln4_197_fu_274_p2 & and_ln115_fu_388_p2);

assign and_ln113_186_fu_400_p2 = (icmp_ln4_198_fu_280_p2 & and_ln113_185_fu_394_p2);

assign and_ln113_187_fu_418_p2 = (and_ln115_fu_388_p2 & and_ln113_197_fu_412_p2);

assign and_ln113_188_fu_436_p2 = (icmp_ln4_200_fu_292_p2 & and_ln115_11_fu_430_p2);

assign and_ln113_189_fu_454_p2 = (and_ln115_11_fu_430_p2 & and_ln113_198_fu_448_p2);

assign and_ln113_190_fu_466_p2 = (xor_ln115_87_fu_460_p2 & icmp_ln4_202_fu_304_p2);

assign and_ln113_191_fu_472_p2 = (icmp_ln4_203_fu_310_p2 & and_ln113_190_fu_466_p2);

assign and_ln113_192_fu_478_p2 = (icmp_ln4_204_fu_316_p2 & and_ln113_191_fu_472_p2);

assign and_ln113_193_fu_484_p2 = (icmp_ln4_205_fu_322_p2 & and_ln113_192_fu_478_p2);

assign and_ln113_194_fu_502_p2 = (xor_ln115_88_fu_490_p2 & and_ln113_199_fu_496_p2);

assign and_ln113_195_fu_508_p2 = (icmp_ln4_207_fu_334_p2 & and_ln113_194_fu_502_p2);

assign and_ln113_196_fu_370_p2 = (xor_ln115_fu_364_p2 & icmp_ln4_196_fu_268_p2);

assign and_ln113_197_fu_412_p2 = (xor_ln115_84_fu_406_p2 & icmp_ln4_199_fu_286_p2);

assign and_ln113_198_fu_448_p2 = (xor_ln115_86_fu_442_p2 & icmp_ln4_201_fu_298_p2);

assign and_ln113_199_fu_496_p2 = (xor_ln115_87_fu_460_p2 & icmp_ln4_206_fu_328_p2);

assign and_ln113_fu_340_p2 = (icmp_ln4_fu_238_p2 & icmp_ln4_192_fu_244_p2);

assign and_ln115_11_fu_430_p2 = (xor_ln115_85_fu_424_p2 & icmp_ln4_fu_238_p2);

assign and_ln115_fu_388_p2 = (xor_ln115_83_fu_382_p2 & and_ln113_fu_340_p2);

assign ap_ready = 1'b1;

assign icmp_ln4_192_fu_244_p2 = (($signed(x_11_val) < $signed(32'd483)) ? 1'b1 : 1'b0);

assign icmp_ln4_193_fu_250_p2 = (($signed(x_17_val) < $signed(32'd507)) ? 1'b1 : 1'b0);

assign icmp_ln4_194_fu_256_p2 = (($signed(x_19_val) < $signed(32'd4793)) ? 1'b1 : 1'b0);

assign icmp_ln4_195_fu_262_p2 = (($signed(x_24_val) < $signed(32'd473)) ? 1'b1 : 1'b0);

assign icmp_ln4_196_fu_268_p2 = (($signed(x_16_val) < $signed(32'd3838)) ? 1'b1 : 1'b0);

assign icmp_ln4_197_fu_274_p2 = (($signed(x_17_val) < $signed(32'd10997)) ? 1'b1 : 1'b0);

assign icmp_ln4_198_fu_280_p2 = (($signed(x_10_val) < $signed(32'd579)) ? 1'b1 : 1'b0);

assign icmp_ln4_199_fu_286_p2 = (($signed(x_24_val) < $signed(32'd6846)) ? 1'b1 : 1'b0);

assign icmp_ln4_200_fu_292_p2 = (($signed(x_23_val) < $signed(32'd486)) ? 1'b1 : 1'b0);

assign icmp_ln4_201_fu_298_p2 = (($signed(x_23_val) < $signed(32'd7176)) ? 1'b1 : 1'b0);

assign icmp_ln4_203_fu_310_p2 = (($signed(x_14_val) < $signed(32'd12877)) ? 1'b1 : 1'b0);

assign icmp_ln4_204_fu_316_p2 = (($signed(x_12_val) < $signed(32'd480)) ? 1'b1 : 1'b0);

assign icmp_ln4_205_fu_322_p2 = (($signed(x_16_val) < $signed(32'd1312)) ? 1'b1 : 1'b0);

assign icmp_ln4_207_fu_334_p2 = (($signed(x_22_val) < $signed(32'd4752)) ? 1'b1 : 1'b0);

assign or_ln128_137_fu_550_p2 = (and_ln113_186_fu_400_p2 | and_ln113_181_fu_346_p2);

assign or_ln128_138_fu_564_p2 = (and_ln113_185_fu_394_p2 | and_ln113_181_fu_346_p2);

assign or_ln128_139_fu_578_p2 = (or_ln128_138_fu_564_p2 | and_ln113_187_fu_418_p2);

assign or_ln128_140_fu_604_p2 = (and_ln113_fu_340_p2 | and_ln113_188_fu_436_p2);

assign or_ln128_141_fu_618_p2 = (or_ln128_140_fu_604_p2 | and_ln113_189_fu_454_p2);

assign or_ln128_142_fu_640_p2 = (icmp_ln4_fu_238_p2 | and_ln113_193_fu_484_p2);

assign or_ln128_143_fu_654_p2 = (icmp_ln4_fu_238_p2 | and_ln113_192_fu_478_p2);

assign or_ln128_144_fu_668_p2 = (icmp_ln4_fu_238_p2 | and_ln113_191_fu_472_p2);

assign or_ln128_145_fu_682_p2 = (icmp_ln4_fu_238_p2 | and_ln113_190_fu_466_p2);

assign or_ln128_146_fu_696_p2 = (or_ln128_145_fu_682_p2 | and_ln113_195_fu_508_p2);

assign or_ln128_147_fu_714_p2 = (or_ln128_145_fu_682_p2 | and_ln113_194_fu_502_p2);

assign or_ln128_fu_524_p2 = (and_ln113_184_fu_376_p2 | and_ln113_182_fu_352_p2);

assign select_ln128_181_fu_538_p3 = ((or_ln128_fu_524_p2[0:0] == 1'b1) ? select_ln128_fu_530_p3 : 2'd3);

assign select_ln128_182_fu_556_p3 = ((and_ln113_181_fu_346_p2[0:0] == 1'b1) ? zext_ln128_31_fu_546_p1 : 3'd4);

assign select_ln128_183_fu_570_p3 = ((or_ln128_137_fu_550_p2[0:0] == 1'b1) ? select_ln128_182_fu_556_p3 : 3'd5);

assign select_ln128_184_fu_584_p3 = ((or_ln128_138_fu_564_p2[0:0] == 1'b1) ? select_ln128_183_fu_570_p3 : 3'd6);

assign select_ln128_185_fu_592_p3 = ((or_ln128_139_fu_578_p2[0:0] == 1'b1) ? select_ln128_184_fu_584_p3 : 3'd7);

assign select_ln128_186_fu_610_p3 = ((and_ln113_fu_340_p2[0:0] == 1'b1) ? zext_ln128_32_fu_600_p1 : 4'd8);

assign select_ln128_187_fu_624_p3 = ((or_ln128_140_fu_604_p2[0:0] == 1'b1) ? select_ln128_186_fu_610_p3 : 4'd9);

assign select_ln128_188_fu_632_p3 = ((or_ln128_141_fu_618_p2[0:0] == 1'b1) ? select_ln128_187_fu_624_p3 : 4'd10);

assign select_ln128_189_fu_646_p3 = ((icmp_ln4_fu_238_p2[0:0] == 1'b1) ? select_ln128_188_fu_632_p3 : 4'd11);

assign select_ln128_190_fu_660_p3 = ((or_ln128_142_fu_640_p2[0:0] == 1'b1) ? select_ln128_189_fu_646_p3 : 4'd12);

assign select_ln128_191_fu_674_p3 = ((or_ln128_143_fu_654_p2[0:0] == 1'b1) ? select_ln128_190_fu_660_p3 : 4'd13);

assign select_ln128_192_fu_688_p3 = ((or_ln128_144_fu_668_p2[0:0] == 1'b1) ? select_ln128_191_fu_674_p3 : 4'd14);

assign select_ln128_193_fu_702_p3 = ((or_ln128_145_fu_682_p2[0:0] == 1'b1) ? select_ln128_192_fu_688_p3 : 4'd15);

assign select_ln128_194_fu_720_p3 = ((or_ln128_146_fu_696_p2[0:0] == 1'b1) ? zext_ln128_33_fu_710_p1 : 5'd16);

assign select_ln128_fu_530_p3 = ((and_ln113_182_fu_352_p2[0:0] == 1'b1) ? zext_ln128_fu_520_p1 : 2'd2);

assign xor_ln115_83_fu_382_p2 = (icmp_ln4_193_fu_250_p2 ^ 1'd1);

assign xor_ln115_84_fu_406_p2 = (icmp_ln4_197_fu_274_p2 ^ 1'd1);

assign xor_ln115_85_fu_424_p2 = (icmp_ln4_192_fu_244_p2 ^ 1'd1);

assign xor_ln115_86_fu_442_p2 = (icmp_ln4_200_fu_292_p2 ^ 1'd1);

assign xor_ln115_87_fu_460_p2 = (icmp_ln4_fu_238_p2 ^ 1'd1);

assign xor_ln115_88_fu_490_p2 = (icmp_ln4_202_fu_304_p2 ^ 1'd1);

assign xor_ln115_fu_364_p2 = (icmp_ln4_194_fu_256_p2 ^ 1'd1);

assign xor_ln128_fu_514_p2 = (1'd1 ^ and_ln113_183_fu_358_p2);

assign zext_ln128_31_fu_546_p1 = select_ln128_181_fu_538_p3;

assign zext_ln128_32_fu_600_p1 = select_ln128_185_fu_592_p3;

assign zext_ln128_33_fu_710_p1 = select_ln128_193_fu_702_p3;

assign zext_ln128_fu_520_p1 = xor_ln128_fu_514_p2;

assign agg_result_fu_736_p37 = 'bx;

assign agg_result_fu_736_p38 = ((or_ln128_147_fu_714_p2[0:0] == 1'b1) ? select_ln128_194_fu_720_p3 : 5'd17);

assign ap_return = agg_result_fu_736_p39;

assign icmp_ln4_202_fu_304_p2 = (($signed(x_19_val) < $signed(32'd2446)) ? 1'b1 : 1'b0);

assign icmp_ln4_206_fu_328_p2 = (($signed(x_21_val) < $signed(32'd3192)) ? 1'b1 : 1'b0);

assign icmp_ln4_fu_238_p2 = (($signed(x_4_val) < $signed(32'd321)) ? 1'b1 : 1'b0);

endmodule //my_prj_accelerator_decision_function_ap_fixed_32_18_5_3_0_ap_fixed_32_18_5_3_0_11
