-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity my_prj_accelerator_decision_function_ap_fixed_32_18_5_3_0_ap_fixed_32_18_5_3_0_17 is
port (
    ap_ready : OUT STD_LOGIC;
    x_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_16_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_18_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_26_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_39_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of my_prj_accelerator_decision_function_ap_fixed_32_18_5_3_0_ap_fixed_32_18_5_3_0_17 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_21E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000011110";
    constant ap_const_lv32_2F4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011110100";
    constant ap_const_lv32_1333 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001001100110011";
    constant ap_const_lv32_124C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001001001001100";
    constant ap_const_lv32_77D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000011101111101";
    constant ap_const_lv32_A00 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000101000000000";
    constant ap_const_lv32_266 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001100110";
    constant ap_const_lv32_75B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000011101011011";
    constant ap_const_lv32_C9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001001";
    constant ap_const_lv32_AE1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000101011100001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv10_197 : STD_LOGIC_VECTOR (9 downto 0) := "0110010111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_2DA : STD_LOGIC_VECTOR (9 downto 0) := "1011011010";
    constant ap_const_lv10_DD : STD_LOGIC_VECTOR (9 downto 0) := "0011011101";
    constant ap_const_lv10_7 : STD_LOGIC_VECTOR (9 downto 0) := "0000000111";
    constant ap_const_lv10_1E : STD_LOGIC_VECTOR (9 downto 0) := "0000011110";
    constant ap_const_lv10_3C : STD_LOGIC_VECTOR (9 downto 0) := "0000111100";
    constant ap_const_lv10_B : STD_LOGIC_VECTOR (9 downto 0) := "0000001011";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln4_122_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_123_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_124_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_129_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_125_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_130_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_126_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_132_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_127_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_46_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_134_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_128_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_135_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_129_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_47_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_130_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_138_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_48_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_131_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln128_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_133_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln128_fu_320_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln128_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_fu_330_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln128_115_fu_338_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln113_136_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln128_21_fu_346_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln128_86_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_116_fu_356_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln128_87_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_117_fu_370_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln128_118_fu_378_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln128_119_fu_386_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln113_137_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln128_22_fu_394_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_88_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_139_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_120_fu_404_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_89_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_121_fu_418_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p23 : STD_LOGIC_VECTOR (9 downto 0);
    signal agg_result_fu_434_p24 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p25 : STD_LOGIC_VECTOR (9 downto 0);
    signal agg_result_fu_434_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal agg_result_fu_434_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component my_prj_accelerator_sparsemux_23_4_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        din3 : IN STD_LOGIC_VECTOR (9 downto 0);
        din4 : IN STD_LOGIC_VECTOR (9 downto 0);
        din5 : IN STD_LOGIC_VECTOR (9 downto 0);
        din6 : IN STD_LOGIC_VECTOR (9 downto 0);
        din7 : IN STD_LOGIC_VECTOR (9 downto 0);
        din8 : IN STD_LOGIC_VECTOR (9 downto 0);
        din9 : IN STD_LOGIC_VECTOR (9 downto 0);
        din10 : IN STD_LOGIC_VECTOR (9 downto 0);
        def : IN STD_LOGIC_VECTOR (9 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    sparsemux_23_4_10_1_1_U198 : component my_prj_accelerator_sparsemux_23_4_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 10,
        CASE1 => "0001",
        din1_WIDTH => 10,
        CASE2 => "0010",
        din2_WIDTH => 10,
        CASE3 => "0011",
        din3_WIDTH => 10,
        CASE4 => "0100",
        din4_WIDTH => 10,
        CASE5 => "0101",
        din5_WIDTH => 10,
        CASE6 => "0110",
        din6_WIDTH => 10,
        CASE7 => "0111",
        din7_WIDTH => 10,
        CASE8 => "1000",
        din8_WIDTH => 10,
        CASE9 => "1001",
        din9_WIDTH => 10,
        CASE10 => "1010",
        din10_WIDTH => 10,
        def_WIDTH => 10,
        sel_WIDTH => 4,
        dout_WIDTH => 10)
    port map (
        din0 => ap_const_lv10_197,
        din1 => ap_const_lv10_0,
        din2 => ap_const_lv10_2DA,
        din3 => ap_const_lv10_DD,
        din4 => ap_const_lv10_7,
        din5 => ap_const_lv10_1E,
        din6 => ap_const_lv10_0,
        din7 => ap_const_lv10_3C,
        din8 => ap_const_lv10_B,
        din9 => ap_const_lv10_0,
        din10 => ap_const_lv10_0,
        def => agg_result_fu_434_p23,
        sel => agg_result_fu_434_p24,
        dout => agg_result_fu_434_p25);




    agg_result_fu_434_p23 <= "XXXXXXXXXX";
    agg_result_fu_434_p24 <= 
        select_ln128_121_fu_418_p3 when (or_ln128_89_fu_412_p2(0) = '1') else 
        ap_const_lv4_A;
    and_ln113_129_fu_224_p2 <= (icmp_ln4_123_fu_170_p2 and and_ln113_fu_218_p2);
    and_ln113_130_fu_230_p2 <= (icmp_ln4_124_fu_176_p2 and and_ln113_129_fu_224_p2);
    and_ln113_131_fu_236_p2 <= (icmp_ln4_125_fu_182_p2 and and_ln113_130_fu_230_p2);
    and_ln113_132_fu_248_p2 <= (xor_ln115_fu_242_p2 and icmp_ln4_126_fu_188_p2);
    and_ln113_133_fu_254_p2 <= (and_ln113_132_fu_248_p2 and and_ln113_129_fu_224_p2);
    and_ln113_134_fu_266_p2 <= (xor_ln115_46_fu_260_p2 and icmp_ln4_127_fu_194_p2);
    and_ln113_135_fu_272_p2 <= (and_ln113_fu_218_p2 and and_ln113_134_fu_266_p2);
    and_ln113_136_fu_278_p2 <= (icmp_ln4_128_fu_200_p2 and and_ln113_135_fu_272_p2);
    and_ln113_137_fu_290_p2 <= (xor_ln115_47_fu_284_p2 and icmp_ln4_129_fu_206_p2);
    and_ln113_138_fu_302_p2 <= (xor_ln115_47_fu_284_p2 and icmp_ln4_130_fu_212_p2);
    and_ln113_139_fu_308_p2 <= (xor_ln115_48_fu_296_p2 and and_ln113_138_fu_302_p2);
    and_ln113_fu_218_p2 <= (icmp_ln4_fu_158_p2 and icmp_ln4_122_fu_164_p2);
    ap_ready <= ap_const_logic_1;
    ap_return <= agg_result_fu_434_p25;
    icmp_ln4_122_fu_164_p2 <= "1" when (signed(x_8_val) < signed(ap_const_lv32_2F4)) else "0";
    icmp_ln4_123_fu_170_p2 <= "1" when (signed(x_16_val) < signed(ap_const_lv32_1333)) else "0";
    icmp_ln4_124_fu_176_p2 <= "1" when (signed(x_26_val) < signed(ap_const_lv32_124C)) else "0";
    icmp_ln4_125_fu_182_p2 <= "1" when (signed(x_18_val) < signed(ap_const_lv32_77D)) else "0";
    icmp_ln4_126_fu_188_p2 <= "1" when (signed(x_18_val) < signed(ap_const_lv32_A00)) else "0";
    icmp_ln4_127_fu_194_p2 <= "1" when (signed(x_10_val) < signed(ap_const_lv32_266)) else "0";
    icmp_ln4_128_fu_200_p2 <= "1" when (signed(x_11_val) < signed(ap_const_lv32_75B)) else "0";
    icmp_ln4_129_fu_206_p2 <= "1" when (signed(x_39_val) < signed(ap_const_lv32_C9)) else "0";
    icmp_ln4_130_fu_212_p2 <= "1" when (signed(x_4_val) < signed(ap_const_lv32_AE1)) else "0";
    icmp_ln4_fu_158_p2 <= "1" when (signed(x_3_val) < signed(ap_const_lv32_21E)) else "0";
    or_ln128_86_fu_350_p2 <= (and_ln113_136_fu_278_p2 or and_ln113_129_fu_224_p2);
    or_ln128_87_fu_364_p2 <= (and_ln113_135_fu_272_p2 or and_ln113_129_fu_224_p2);
    or_ln128_88_fu_398_p2 <= (icmp_ln4_fu_158_p2 or and_ln113_137_fu_290_p2);
    or_ln128_89_fu_412_p2 <= (or_ln128_88_fu_398_p2 or and_ln113_139_fu_308_p2);
    or_ln128_fu_324_p2 <= (and_ln113_133_fu_254_p2 or and_ln113_130_fu_230_p2);
    select_ln128_115_fu_338_p3 <= 
        select_ln128_fu_330_p3 when (or_ln128_fu_324_p2(0) = '1') else 
        ap_const_lv2_3;
    select_ln128_116_fu_356_p3 <= 
        zext_ln128_21_fu_346_p1 when (and_ln113_129_fu_224_p2(0) = '1') else 
        ap_const_lv3_4;
    select_ln128_117_fu_370_p3 <= 
        select_ln128_116_fu_356_p3 when (or_ln128_86_fu_350_p2(0) = '1') else 
        ap_const_lv3_5;
    select_ln128_118_fu_378_p3 <= 
        select_ln128_117_fu_370_p3 when (or_ln128_87_fu_364_p2(0) = '1') else 
        ap_const_lv3_6;
    select_ln128_119_fu_386_p3 <= 
        select_ln128_118_fu_378_p3 when (and_ln113_fu_218_p2(0) = '1') else 
        ap_const_lv3_7;
    select_ln128_120_fu_404_p3 <= 
        zext_ln128_22_fu_394_p1 when (icmp_ln4_fu_158_p2(0) = '1') else 
        ap_const_lv4_8;
    select_ln128_121_fu_418_p3 <= 
        select_ln128_120_fu_404_p3 when (or_ln128_88_fu_398_p2(0) = '1') else 
        ap_const_lv4_9;
    select_ln128_fu_330_p3 <= 
        zext_ln128_fu_320_p1 when (and_ln113_130_fu_230_p2(0) = '1') else 
        ap_const_lv2_2;
    xor_ln115_46_fu_260_p2 <= (icmp_ln4_123_fu_170_p2 xor ap_const_lv1_1);
    xor_ln115_47_fu_284_p2 <= (icmp_ln4_fu_158_p2 xor ap_const_lv1_1);
    xor_ln115_48_fu_296_p2 <= (icmp_ln4_129_fu_206_p2 xor ap_const_lv1_1);
    xor_ln115_fu_242_p2 <= (icmp_ln4_124_fu_176_p2 xor ap_const_lv1_1);
    xor_ln128_fu_314_p2 <= (ap_const_lv1_1 xor and_ln113_131_fu_236_p2);
    zext_ln128_21_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln128_115_fu_338_p3),3));
    zext_ln128_22_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln128_119_fu_386_p3),4));
    zext_ln128_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln128_fu_314_p2),2));
end behav;
