-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity my_prj_accelerator_decision_function_ap_fixed_32_18_5_3_0_ap_fixed_32_18_5_3_0_2 is
port (
    ap_ready : OUT STD_LOGIC;
    x_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_16_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_21_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_23_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_26_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_27_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_32_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_33_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_37_val : IN STD_LOGIC_VECTOR (31 downto 0);
    x_49_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of my_prj_accelerator_decision_function_ap_fixed_32_18_5_3_0_ap_fixed_32_18_5_3_0_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010010";
    constant ap_const_lv32_1FB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111011";
    constant ap_const_lv32_29B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010011011";
    constant ap_const_lv32_1249 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001001001001001";
    constant ap_const_lv32_7B2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000011110110010";
    constant ap_const_lv32_CC4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000110011000100";
    constant ap_const_lv32_AC5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000101011000101";
    constant ap_const_lv32_3705 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000011011100000101";
    constant ap_const_lv32_4E5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010011100101";
    constant ap_const_lv32_1EC8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001111011001000";
    constant ap_const_lv32_30F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100001111";
    constant ap_const_lv32_1014 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001000000010100";
    constant ap_const_lv32_12F7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001001011110111";
    constant ap_const_lv32_2814 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000010100000010100";
    constant ap_const_lv32_22E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000101110";
    constant ap_const_lv32_4BB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010010111011";
    constant ap_const_lv32_1CA5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001110010100101";
    constant ap_const_lv32_E28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000111000101000";
    constant ap_const_lv32_6A6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000011010100110";
    constant ap_const_lv32_15B9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001010110111001";
    constant ap_const_lv32_1C60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001110001100000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv10_1D7 : STD_LOGIC_VECTOR (9 downto 0) := "0111010111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_2FC : STD_LOGIC_VECTOR (9 downto 0) := "1011111100";
    constant ap_const_lv10_324 : STD_LOGIC_VECTOR (9 downto 0) := "1100100100";
    constant ap_const_lv10_4D : STD_LOGIC_VECTOR (9 downto 0) := "0001001101";
    constant ap_const_lv10_333 : STD_LOGIC_VECTOR (9 downto 0) := "1100110011";
    constant ap_const_lv10_1D : STD_LOGIC_VECTOR (9 downto 0) := "0000011101";
    constant ap_const_lv10_36 : STD_LOGIC_VECTOR (9 downto 0) := "0000110110";
    constant ap_const_lv10_B8 : STD_LOGIC_VECTOR (9 downto 0) := "0010111000";
    constant ap_const_lv10_8 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_const_lv10_D : STD_LOGIC_VECTOR (9 downto 0) := "0000001101";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln4_37_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_38_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_39_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_35_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_40_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_36_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_41_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_54_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_13_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_42_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_43_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_39_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_44_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_14_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_55_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_15_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_45_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_2_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_46_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_42_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_47_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_43_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_48_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_16_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_56_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_49_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_17_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_57_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_50_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_18_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_51_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_47_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_52_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_48_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_53_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_49_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_54_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_19_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_58_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_55_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_20_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_59_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln4_56_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_60_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_21_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_37_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln128_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_38_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln128_fu_630_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln128_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_fu_640_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln128_35_fu_648_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal and_ln113_40_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln128_7_fu_656_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln128_27_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_36_fu_666_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln128_28_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_41_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_37_fu_680_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln128_29_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_38_fu_694_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln128_39_fu_702_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln113_44_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln128_8_fu_710_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_30_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_40_fu_720_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_31_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_45_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_41_fu_734_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_32_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_42_fu_748_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_33_fu_756_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_46_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_43_fu_762_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_34_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_44_fu_776_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln113_50_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_45_fu_784_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_35_fu_792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_46_fu_798_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln128_47_fu_812_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln128_36_fu_806_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_51_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln128_9_fu_820_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln128_37_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_48_fu_830_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln128_38_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_52_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_49_fu_844_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln128_39_fu_852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_50_fu_858_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln128_40_fu_866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_53_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_51_fu_872_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln128_41_fu_880_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln128_52_fu_886_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p45 : STD_LOGIC_VECTOR (9 downto 0);
    signal agg_result_fu_902_p46 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p47 : STD_LOGIC_VECTOR (9 downto 0);
    signal agg_result_fu_902_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal agg_result_fu_902_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component my_prj_accelerator_sparsemux_45_5_10_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        din3 : IN STD_LOGIC_VECTOR (9 downto 0);
        din4 : IN STD_LOGIC_VECTOR (9 downto 0);
        din5 : IN STD_LOGIC_VECTOR (9 downto 0);
        din6 : IN STD_LOGIC_VECTOR (9 downto 0);
        din7 : IN STD_LOGIC_VECTOR (9 downto 0);
        din8 : IN STD_LOGIC_VECTOR (9 downto 0);
        din9 : IN STD_LOGIC_VECTOR (9 downto 0);
        din10 : IN STD_LOGIC_VECTOR (9 downto 0);
        din11 : IN STD_LOGIC_VECTOR (9 downto 0);
        din12 : IN STD_LOGIC_VECTOR (9 downto 0);
        din13 : IN STD_LOGIC_VECTOR (9 downto 0);
        din14 : IN STD_LOGIC_VECTOR (9 downto 0);
        din15 : IN STD_LOGIC_VECTOR (9 downto 0);
        din16 : IN STD_LOGIC_VECTOR (9 downto 0);
        din17 : IN STD_LOGIC_VECTOR (9 downto 0);
        din18 : IN STD_LOGIC_VECTOR (9 downto 0);
        din19 : IN STD_LOGIC_VECTOR (9 downto 0);
        din20 : IN STD_LOGIC_VECTOR (9 downto 0);
        din21 : IN STD_LOGIC_VECTOR (9 downto 0);
        def : IN STD_LOGIC_VECTOR (9 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    sparsemux_45_5_10_1_1_U152 : component my_prj_accelerator_sparsemux_45_5_10_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 10,
        CASE1 => "00001",
        din1_WIDTH => 10,
        CASE2 => "00010",
        din2_WIDTH => 10,
        CASE3 => "00011",
        din3_WIDTH => 10,
        CASE4 => "00100",
        din4_WIDTH => 10,
        CASE5 => "00101",
        din5_WIDTH => 10,
        CASE6 => "00110",
        din6_WIDTH => 10,
        CASE7 => "00111",
        din7_WIDTH => 10,
        CASE8 => "01000",
        din8_WIDTH => 10,
        CASE9 => "01001",
        din9_WIDTH => 10,
        CASE10 => "01010",
        din10_WIDTH => 10,
        CASE11 => "01011",
        din11_WIDTH => 10,
        CASE12 => "01100",
        din12_WIDTH => 10,
        CASE13 => "01101",
        din13_WIDTH => 10,
        CASE14 => "01110",
        din14_WIDTH => 10,
        CASE15 => "01111",
        din15_WIDTH => 10,
        CASE16 => "10000",
        din16_WIDTH => 10,
        CASE17 => "10001",
        din17_WIDTH => 10,
        CASE18 => "10010",
        din18_WIDTH => 10,
        CASE19 => "10011",
        din19_WIDTH => 10,
        CASE20 => "10100",
        din20_WIDTH => 10,
        CASE21 => "10101",
        din21_WIDTH => 10,
        def_WIDTH => 10,
        sel_WIDTH => 5,
        dout_WIDTH => 10)
    port map (
        din0 => ap_const_lv10_1D7,
        din1 => ap_const_lv10_0,
        din2 => ap_const_lv10_2FC,
        din3 => ap_const_lv10_324,
        din4 => ap_const_lv10_4D,
        din5 => ap_const_lv10_333,
        din6 => ap_const_lv10_333,
        din7 => ap_const_lv10_1D,
        din8 => ap_const_lv10_36,
        din9 => ap_const_lv10_0,
        din10 => ap_const_lv10_0,
        din11 => ap_const_lv10_B8,
        din12 => ap_const_lv10_333,
        din13 => ap_const_lv10_0,
        din14 => ap_const_lv10_8,
        din15 => ap_const_lv10_0,
        din16 => ap_const_lv10_0,
        din17 => ap_const_lv10_333,
        din18 => ap_const_lv10_0,
        din19 => ap_const_lv10_D,
        din20 => ap_const_lv10_0,
        din21 => ap_const_lv10_0,
        def => agg_result_fu_902_p45,
        sel => agg_result_fu_902_p46,
        dout => agg_result_fu_902_p47);




    agg_result_fu_902_p45 <= "XXXXXXXXXX";
    agg_result_fu_902_p46 <= 
        select_ln128_52_fu_886_p3 when (or_ln128_41_fu_880_p2(0) = '1') else 
        ap_const_lv5_15;
    and_ln113_35_fu_396_p2 <= (icmp_ln4_38_fu_276_p2 and and_ln113_fu_390_p2);
    and_ln113_36_fu_402_p2 <= (icmp_ln4_39_fu_282_p2 and and_ln113_35_fu_396_p2);
    and_ln113_37_fu_408_p2 <= (icmp_ln4_40_fu_288_p2 and and_ln113_36_fu_402_p2);
    and_ln113_38_fu_426_p2 <= (and_ln113_54_fu_420_p2 and and_ln113_35_fu_396_p2);
    and_ln113_39_fu_444_p2 <= (icmp_ln4_42_fu_300_p2 and and_ln115_fu_438_p2);
    and_ln113_40_fu_450_p2 <= (icmp_ln4_43_fu_306_p2 and and_ln113_39_fu_444_p2);
    and_ln113_41_fu_468_p2 <= (and_ln115_fu_438_p2 and and_ln113_55_fu_462_p2);
    and_ln113_42_fu_486_p2 <= (icmp_ln4_45_fu_318_p2 and and_ln115_2_fu_480_p2);
    and_ln113_43_fu_492_p2 <= (icmp_ln4_46_fu_324_p2 and and_ln113_42_fu_486_p2);
    and_ln113_44_fu_498_p2 <= (icmp_ln4_47_fu_330_p2 and and_ln113_43_fu_492_p2);
    and_ln113_45_fu_516_p2 <= (and_ln113_56_fu_510_p2 and and_ln113_42_fu_486_p2);
    and_ln113_46_fu_534_p2 <= (and_ln115_2_fu_480_p2 and and_ln113_57_fu_528_p2);
    and_ln113_47_fu_546_p2 <= (xor_ln115_18_fu_540_p2 and icmp_ln4_50_fu_348_p2);
    and_ln113_48_fu_552_p2 <= (icmp_ln4_51_fu_354_p2 and and_ln113_47_fu_546_p2);
    and_ln113_49_fu_558_p2 <= (icmp_ln4_52_fu_360_p2 and and_ln113_48_fu_552_p2);
    and_ln113_50_fu_564_p2 <= (icmp_ln4_53_fu_366_p2 and and_ln113_49_fu_558_p2);
    and_ln113_51_fu_582_p2 <= (and_ln113_58_fu_576_p2 and and_ln113_48_fu_552_p2);
    and_ln113_52_fu_600_p2 <= (and_ln113_59_fu_594_p2 and and_ln113_47_fu_546_p2);
    and_ln113_53_fu_618_p2 <= (xor_ln115_21_fu_606_p2 and and_ln113_60_fu_612_p2);
    and_ln113_54_fu_420_p2 <= (xor_ln115_fu_414_p2 and icmp_ln4_41_fu_294_p2);
    and_ln113_55_fu_462_p2 <= (xor_ln115_14_fu_456_p2 and icmp_ln4_44_fu_312_p2);
    and_ln113_56_fu_510_p2 <= (xor_ln115_16_fu_504_p2 and icmp_ln4_48_fu_336_p2);
    and_ln113_57_fu_528_p2 <= (xor_ln115_17_fu_522_p2 and icmp_ln4_49_fu_342_p2);
    and_ln113_58_fu_576_p2 <= (xor_ln115_19_fu_570_p2 and icmp_ln4_54_fu_372_p2);
    and_ln113_59_fu_594_p2 <= (xor_ln115_20_fu_588_p2 and icmp_ln4_55_fu_378_p2);
    and_ln113_60_fu_612_p2 <= (xor_ln115_18_fu_540_p2 and icmp_ln4_56_fu_384_p2);
    and_ln113_fu_390_p2 <= (icmp_ln4_fu_264_p2 and icmp_ln4_37_fu_270_p2);
    and_ln115_2_fu_480_p2 <= (xor_ln115_15_fu_474_p2 and icmp_ln4_fu_264_p2);
    and_ln115_fu_438_p2 <= (xor_ln115_13_fu_432_p2 and and_ln113_fu_390_p2);
    ap_ready <= ap_const_logic_1;
    ap_return <= agg_result_fu_902_p47;
    icmp_ln4_37_fu_270_p2 <= "1" when (signed(x_33_val) < signed(ap_const_lv32_1FB)) else "0";
    icmp_ln4_38_fu_276_p2 <= "1" when (signed(x_11_val) < signed(ap_const_lv32_29B)) else "0";
    icmp_ln4_39_fu_282_p2 <= "1" when (signed(x_26_val) < signed(ap_const_lv32_1249)) else "0";
    icmp_ln4_40_fu_288_p2 <= "1" when (signed(x_1_val) < signed(ap_const_lv32_7B2)) else "0";
    icmp_ln4_41_fu_294_p2 <= "1" when (signed(x_8_val) < signed(ap_const_lv32_CC4)) else "0";
    icmp_ln4_42_fu_300_p2 <= "1" when (signed(x_26_val) < signed(ap_const_lv32_AC5)) else "0";
    icmp_ln4_43_fu_306_p2 <= "1" when (signed(x_11_val) < signed(ap_const_lv32_3705)) else "0";
    icmp_ln4_44_fu_312_p2 <= "1" when (signed(x_49_val) < signed(ap_const_lv32_4E5)) else "0";
    icmp_ln4_45_fu_318_p2 <= "1" when (signed(x_10_val) < signed(ap_const_lv32_1EC8)) else "0";
    icmp_ln4_46_fu_324_p2 <= "1" when (signed(x_11_val) < signed(ap_const_lv32_30F)) else "0";
    icmp_ln4_47_fu_330_p2 <= "1" when (signed(x_27_val) < signed(ap_const_lv32_1014)) else "0";
    icmp_ln4_48_fu_336_p2 <= "1" when (signed(x_26_val) < signed(ap_const_lv32_12F7)) else "0";
    icmp_ln4_49_fu_342_p2 <= "1" when (signed(x_33_val) < signed(ap_const_lv32_2814)) else "0";
    icmp_ln4_50_fu_348_p2 <= "1" when (signed(x_5_val) < signed(ap_const_lv32_22E)) else "0";
    icmp_ln4_51_fu_354_p2 <= "1" when (signed(x_32_val) < signed(ap_const_lv32_4BB)) else "0";
    icmp_ln4_52_fu_360_p2 <= "1" when (signed(x_23_val) < signed(ap_const_lv32_1CA5)) else "0";
    icmp_ln4_53_fu_366_p2 <= "1" when (signed(x_37_val) < signed(ap_const_lv32_E28)) else "0";
    icmp_ln4_54_fu_372_p2 <= "1" when (signed(x_26_val) < signed(ap_const_lv32_6A6)) else "0";
    icmp_ln4_55_fu_378_p2 <= "1" when (signed(x_21_val) < signed(ap_const_lv32_15B9)) else "0";
    icmp_ln4_56_fu_384_p2 <= "1" when (signed(x_16_val) < signed(ap_const_lv32_1C60)) else "0";
    icmp_ln4_fu_264_p2 <= "1" when (signed(x_23_val) < signed(ap_const_lv32_1D2)) else "0";
    or_ln128_27_fu_660_p2 <= (and_ln113_40_fu_450_p2 or and_ln113_35_fu_396_p2);
    or_ln128_28_fu_674_p2 <= (and_ln113_39_fu_444_p2 or and_ln113_35_fu_396_p2);
    or_ln128_29_fu_688_p2 <= (or_ln128_28_fu_674_p2 or and_ln113_41_fu_468_p2);
    or_ln128_30_fu_714_p2 <= (and_ln113_fu_390_p2 or and_ln113_44_fu_498_p2);
    or_ln128_31_fu_728_p2 <= (and_ln113_fu_390_p2 or and_ln113_43_fu_492_p2);
    or_ln128_32_fu_742_p2 <= (or_ln128_31_fu_728_p2 or and_ln113_45_fu_516_p2);
    or_ln128_33_fu_756_p2 <= (and_ln113_fu_390_p2 or and_ln113_42_fu_486_p2);
    or_ln128_34_fu_770_p2 <= (or_ln128_33_fu_756_p2 or and_ln113_46_fu_534_p2);
    or_ln128_35_fu_792_p2 <= (icmp_ln4_fu_264_p2 or and_ln113_50_fu_564_p2);
    or_ln128_36_fu_806_p2 <= (icmp_ln4_fu_264_p2 or and_ln113_49_fu_558_p2);
    or_ln128_37_fu_824_p2 <= (or_ln128_36_fu_806_p2 or and_ln113_51_fu_582_p2);
    or_ln128_38_fu_838_p2 <= (icmp_ln4_fu_264_p2 or and_ln113_48_fu_552_p2);
    or_ln128_39_fu_852_p2 <= (or_ln128_38_fu_838_p2 or and_ln113_52_fu_600_p2);
    or_ln128_40_fu_866_p2 <= (icmp_ln4_fu_264_p2 or and_ln113_47_fu_546_p2);
    or_ln128_41_fu_880_p2 <= (or_ln128_40_fu_866_p2 or and_ln113_53_fu_618_p2);
    or_ln128_fu_634_p2 <= (and_ln113_38_fu_426_p2 or and_ln113_36_fu_402_p2);
    select_ln128_35_fu_648_p3 <= 
        select_ln128_fu_640_p3 when (or_ln128_fu_634_p2(0) = '1') else 
        ap_const_lv2_3;
    select_ln128_36_fu_666_p3 <= 
        zext_ln128_7_fu_656_p1 when (and_ln113_35_fu_396_p2(0) = '1') else 
        ap_const_lv3_4;
    select_ln128_37_fu_680_p3 <= 
        select_ln128_36_fu_666_p3 when (or_ln128_27_fu_660_p2(0) = '1') else 
        ap_const_lv3_5;
    select_ln128_38_fu_694_p3 <= 
        select_ln128_37_fu_680_p3 when (or_ln128_28_fu_674_p2(0) = '1') else 
        ap_const_lv3_6;
    select_ln128_39_fu_702_p3 <= 
        select_ln128_38_fu_694_p3 when (or_ln128_29_fu_688_p2(0) = '1') else 
        ap_const_lv3_7;
    select_ln128_40_fu_720_p3 <= 
        zext_ln128_8_fu_710_p1 when (and_ln113_fu_390_p2(0) = '1') else 
        ap_const_lv4_8;
    select_ln128_41_fu_734_p3 <= 
        select_ln128_40_fu_720_p3 when (or_ln128_30_fu_714_p2(0) = '1') else 
        ap_const_lv4_9;
    select_ln128_42_fu_748_p3 <= 
        select_ln128_41_fu_734_p3 when (or_ln128_31_fu_728_p2(0) = '1') else 
        ap_const_lv4_A;
    select_ln128_43_fu_762_p3 <= 
        select_ln128_42_fu_748_p3 when (or_ln128_32_fu_742_p2(0) = '1') else 
        ap_const_lv4_B;
    select_ln128_44_fu_776_p3 <= 
        select_ln128_43_fu_762_p3 when (or_ln128_33_fu_756_p2(0) = '1') else 
        ap_const_lv4_C;
    select_ln128_45_fu_784_p3 <= 
        select_ln128_44_fu_776_p3 when (or_ln128_34_fu_770_p2(0) = '1') else 
        ap_const_lv4_D;
    select_ln128_46_fu_798_p3 <= 
        select_ln128_45_fu_784_p3 when (icmp_ln4_fu_264_p2(0) = '1') else 
        ap_const_lv4_E;
    select_ln128_47_fu_812_p3 <= 
        select_ln128_46_fu_798_p3 when (or_ln128_35_fu_792_p2(0) = '1') else 
        ap_const_lv4_F;
    select_ln128_48_fu_830_p3 <= 
        zext_ln128_9_fu_820_p1 when (or_ln128_36_fu_806_p2(0) = '1') else 
        ap_const_lv5_10;
    select_ln128_49_fu_844_p3 <= 
        select_ln128_48_fu_830_p3 when (or_ln128_37_fu_824_p2(0) = '1') else 
        ap_const_lv5_11;
    select_ln128_50_fu_858_p3 <= 
        select_ln128_49_fu_844_p3 when (or_ln128_38_fu_838_p2(0) = '1') else 
        ap_const_lv5_12;
    select_ln128_51_fu_872_p3 <= 
        select_ln128_50_fu_858_p3 when (or_ln128_39_fu_852_p2(0) = '1') else 
        ap_const_lv5_13;
    select_ln128_52_fu_886_p3 <= 
        select_ln128_51_fu_872_p3 when (or_ln128_40_fu_866_p2(0) = '1') else 
        ap_const_lv5_14;
    select_ln128_fu_640_p3 <= 
        zext_ln128_fu_630_p1 when (and_ln113_36_fu_402_p2(0) = '1') else 
        ap_const_lv2_2;
    xor_ln115_13_fu_432_p2 <= (icmp_ln4_38_fu_276_p2 xor ap_const_lv1_1);
    xor_ln115_14_fu_456_p2 <= (icmp_ln4_42_fu_300_p2 xor ap_const_lv1_1);
    xor_ln115_15_fu_474_p2 <= (icmp_ln4_37_fu_270_p2 xor ap_const_lv1_1);
    xor_ln115_16_fu_504_p2 <= (icmp_ln4_46_fu_324_p2 xor ap_const_lv1_1);
    xor_ln115_17_fu_522_p2 <= (icmp_ln4_45_fu_318_p2 xor ap_const_lv1_1);
    xor_ln115_18_fu_540_p2 <= (icmp_ln4_fu_264_p2 xor ap_const_lv1_1);
    xor_ln115_19_fu_570_p2 <= (icmp_ln4_52_fu_360_p2 xor ap_const_lv1_1);
    xor_ln115_20_fu_588_p2 <= (icmp_ln4_51_fu_354_p2 xor ap_const_lv1_1);
    xor_ln115_21_fu_606_p2 <= (icmp_ln4_50_fu_348_p2 xor ap_const_lv1_1);
    xor_ln115_fu_414_p2 <= (icmp_ln4_39_fu_282_p2 xor ap_const_lv1_1);
    xor_ln128_fu_624_p2 <= (ap_const_lv1_1 xor and_ln113_37_fu_408_p2);
    zext_ln128_7_fu_656_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln128_35_fu_648_p3),3));
    zext_ln128_8_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln128_39_fu_702_p3),4));
    zext_ln128_9_fu_820_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln128_47_fu_812_p3),5));
    zext_ln128_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln128_fu_624_p2),2));
end behav;
