set(DRIVER_INSTANCES "my_prj_accelerator@a0020000")
set(DRIVER_PROP_0_LIST "xlnx,my-prj-accelerator-1.0;0xa0020000")
set(DRIVER_OPTPROP_0_LIST "")
list(APPEND TOTAL_DRIVER_PROP_LIST DRIVER_PROP_0_LIST)
