// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module my_prj_accelerator_sigmoid_ap_fixed_32_15_5_3_0_ap_fixed_32_15_5_3_0_sigmoid_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_val,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] data_val;
output  [16:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [9:0] sigmoid_table_address0;
wire   [9:0] sigmoid_table_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln121_fu_189_p1;
wire    ap_block_pp0_stage0;
reg    sigmoid_table_ce0_local;
wire   [10:0] trunc_ln115_fu_91_p1;
wire   [16:0] tmp_2_fu_95_p3;
wire   [20:0] tmp_3_fu_73_p4;
wire   [0:0] icmp_ln115_fu_103_p2;
wire   [20:0] add_ln115_fu_109_p2;
wire   [0:0] tmp_fu_83_p3;
wire   [20:0] select_ln115_fu_115_p3;
wire   [20:0] data_round_fu_123_p3;
wire  signed [21:0] sext_ln112_fu_131_p1;
wire   [21:0] index_fu_135_p2;
wire   [0:0] tmp_1_fu_145_p3;
wire   [20:0] trunc_ln113_fu_141_p1;
wire   [20:0] index_1_fu_153_p3;
wire   [10:0] tmp_4_fu_165_p4;
wire   [0:0] icmp_ln119_fu_175_p2;
wire   [9:0] trunc_ln113_1_fu_161_p1;
wire   [9:0] index_2_fu_181_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

my_prj_accelerator_sigmoid_ap_fixed_32_15_5_3_0_ap_fixed_32_15_5_3_0_sigmoid_config9_s_sigmoid_tbkb #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sigmoid_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_table_address0),
    .ce0(sigmoid_table_ce0_local),
    .q0(sigmoid_table_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sigmoid_table_ce0_local = 1'b1;
    end else begin
        sigmoid_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln115_fu_109_p2 = (tmp_3_fu_73_p4 + 21'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = {{sigmoid_table_q0}, {7'd0}};

assign data_round_fu_123_p3 = ((tmp_fu_83_p3[0:0] == 1'b1) ? select_ln115_fu_115_p3 : tmp_3_fu_73_p4);

assign icmp_ln115_fu_103_p2 = ((tmp_2_fu_95_p3 != 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_175_p2 = ((tmp_4_fu_165_p4 != 11'd0) ? 1'b1 : 1'b0);

assign index_1_fu_153_p3 = ((tmp_1_fu_145_p3[0:0] == 1'b1) ? 21'd0 : trunc_ln113_fu_141_p1);

assign index_2_fu_181_p3 = ((icmp_ln119_fu_175_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln113_1_fu_161_p1);

assign index_fu_135_p2 = ($signed(sext_ln112_fu_131_p1) + $signed(22'd512));

assign select_ln115_fu_115_p3 = ((icmp_ln115_fu_103_p2[0:0] == 1'b1) ? add_ln115_fu_109_p2 : tmp_3_fu_73_p4);

assign sext_ln112_fu_131_p1 = $signed(data_round_fu_123_p3);

assign sigmoid_table_address0 = zext_ln121_fu_189_p1;

assign tmp_1_fu_145_p3 = index_fu_135_p2[32'd21];

assign tmp_2_fu_95_p3 = {{trunc_ln115_fu_91_p1}, {6'd0}};

assign tmp_3_fu_73_p4 = {{data_val[31:11]}};

assign tmp_4_fu_165_p4 = {{index_1_fu_153_p3[20:10]}};

assign tmp_fu_83_p3 = data_val[32'd31];

assign trunc_ln113_1_fu_161_p1 = index_1_fu_153_p3[9:0];

assign trunc_ln113_fu_141_p1 = index_fu_135_p2[20:0];

assign trunc_ln115_fu_91_p1 = data_val[10:0];

assign zext_ln121_fu_189_p1 = index_2_fu_181_p3;

endmodule //my_prj_accelerator_sigmoid_ap_fixed_32_15_5_3_0_ap_fixed_32_15_5_3_0_sigmoid_config9_s
