// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module my_prj_accelerator_Loop_VITIS_LOOP_95_1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        N_dout,
        N_empty_n,
        N_read,
        N_num_data_valid,
        N_fifo_cap,
        x_TDATA,
        x_TVALID,
        x_TREADY,
        x_TKEEP,
        x_TSTRB,
        x_TLAST,
        p_read,
        result_TDATA,
        result_TVALID,
        result_TREADY,
        result_TKEEP,
        result_TSTRB,
        result_TLAST
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] N_dout;
input   N_empty_n;
output   N_read;
input  [2:0] N_num_data_valid;
input  [2:0] N_fifo_cap;
input  [31:0] x_TDATA;
input   x_TVALID;
output   x_TREADY;
input  [3:0] x_TKEEP;
input  [3:0] x_TSTRB;
input  [0:0] x_TLAST;
input  [31:0] p_read;
output  [31:0] result_TDATA;
output   result_TVALID;
input   result_TREADY;
output  [3:0] result_TKEEP;
output  [3:0] result_TSTRB;
output  [0:0] result_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg N_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    N_blk_n;
wire    grp_copy_output_fu_273_result_TDATA_blk_n;
reg    result_TDATA_blk_n;
wire    ap_CS_fsm_state6;
reg   [31:0] p_read_67_reg_453;
reg    ap_block_state1;
reg   [31:0] N_read_reg_608;
wire   [0:0] icmp_ln104_fu_310_p2;
reg   [0:0] icmp_ln104_reg_622;
wire    ap_CS_fsm_state2;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_done;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_idle;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_ready;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_x_TREADY;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i49_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i49_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i47_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i47_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i45_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i45_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i43_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i43_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i41_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i41_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i39_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i39_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i37_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i37_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i35_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i35_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i33_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i33_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i31_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i31_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i29_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i29_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i27_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i27_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i25_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i25_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i23_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i23_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i21_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i21_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i19_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i19_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i17_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i17_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i15_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i15_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i13_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i13_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i11_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i11_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i9_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i9_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i7_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i7_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i5_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i5_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i3_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i3_i_i_out_ap_vld;
wire   [31:0] grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i1_i_i_out;
wire    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i1_i_i_out_ap_vld;
wire   [16:0] grp_myproject_fu_237_layer9_out;
wire    grp_myproject_fu_237_ap_start;
wire    grp_myproject_fu_237_layer9_out_ap_vld;
wire    grp_myproject_fu_237_ap_done;
wire    grp_myproject_fu_237_ap_ready;
wire    grp_myproject_fu_237_ap_idle;
reg    grp_myproject_fu_237_ap_continue;
wire    grp_copy_output_fu_273_ap_start;
wire    grp_copy_output_fu_273_ap_done;
wire    grp_copy_output_fu_273_ap_idle;
wire    grp_copy_output_fu_273_ap_ready;
wire    grp_copy_output_fu_273_result_TREADY;
wire   [31:0] grp_copy_output_fu_273_result_TDATA;
wire    grp_copy_output_fu_273_result_TVALID;
wire   [3:0] grp_copy_output_fu_273_result_TKEEP;
wire   [3:0] grp_copy_output_fu_273_result_TSTRB;
wire   [0:0] grp_copy_output_fu_273_result_TLAST;
reg    grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start_reg;
wire   [0:0] icmp_ln95_fu_299_p2;
wire    ap_CS_fsm_state3;
reg    grp_myproject_fu_237_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    ap_sync_reg_grp_myproject_fu_237_ap_ready;
reg    ap_sync_reg_grp_myproject_fu_237_ap_done;
reg    ap_block_state5_on_subcall_done;
wire    ap_sync_grp_myproject_fu_237_ap_ready;
reg   [16:0] result_int_fu_184;
reg    grp_copy_output_fu_273_ap_start_reg;
reg   [7:0] ap_NS_fsm;
wire    ap_NS_fsm_state6;
reg   [31:0] result_TDATA_reg;
reg   [3:0] result_TKEEP_reg;
reg   [3:0] result_TSTRB_reg;
reg   [0:0] result_TLAST_reg;
reg   [30:0] n_fu_80;
wire   [30:0] n_2_fu_304_p2;
wire   [31:0] zext_ln95_fu_295_p1;
wire    ap_CS_fsm_state8;
wire    regslice_both_result_V_data_V_U_apdone_blk;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_x_V_data_V_U_apdone_blk;
wire   [31:0] x_TDATA_int_regslice;
wire    x_TVALID_int_regslice;
reg    x_TREADY_int_regslice;
wire    regslice_both_x_V_data_V_U_ack_in;
wire    regslice_both_x_V_keep_V_U_apdone_blk;
wire   [3:0] x_TKEEP_int_regslice;
wire    regslice_both_x_V_keep_V_U_vld_out;
wire    regslice_both_x_V_keep_V_U_ack_in;
wire    regslice_both_x_V_strb_V_U_apdone_blk;
wire   [3:0] x_TSTRB_int_regslice;
wire    regslice_both_x_V_strb_V_U_vld_out;
wire    regslice_both_x_V_strb_V_U_ack_in;
wire    regslice_both_x_V_last_V_U_apdone_blk;
wire   [0:0] x_TLAST_int_regslice;
wire    regslice_both_x_V_last_V_U_vld_out;
wire    regslice_both_x_V_last_V_U_ack_in;
reg   [31:0] result_TDATA_int_regslice;
wire    result_TVALID_int_regslice;
wire    result_TREADY_int_regslice;
wire    regslice_both_result_V_data_V_U_vld_out;
wire    regslice_both_result_V_keep_V_U_apdone_blk;
reg   [3:0] result_TKEEP_int_regslice;
wire    regslice_both_result_V_keep_V_U_ack_in_dummy;
wire    regslice_both_result_V_keep_V_U_vld_out;
wire    regslice_both_result_V_strb_V_U_apdone_blk;
reg   [3:0] result_TSTRB_int_regslice;
wire    regslice_both_result_V_strb_V_U_ack_in_dummy;
wire    regslice_both_result_V_strb_V_U_vld_out;
wire    regslice_both_result_V_last_V_U_apdone_blk;
reg   [0:0] result_TLAST_int_regslice;
wire    regslice_both_result_V_last_V_U_ack_in_dummy;
wire    regslice_both_result_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start_reg = 1'b0;
#0 grp_myproject_fu_237_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_myproject_fu_237_ap_ready = 1'b0;
#0 ap_sync_reg_grp_myproject_fu_237_ap_done = 1'b0;
#0 grp_copy_output_fu_273_ap_start_reg = 1'b0;
#0 n_fu_80 = 31'd0;
end

my_prj_accelerator_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1 grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start),
    .ap_done(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_done),
    .ap_idle(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_idle),
    .ap_ready(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_ready),
    .x_TVALID(x_TVALID_int_regslice),
    .x_TDATA(x_TDATA_int_regslice),
    .x_TREADY(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_x_TREADY),
    .x_TKEEP(x_TKEEP_int_regslice),
    .x_TSTRB(x_TSTRB_int_regslice),
    .x_TLAST(x_TLAST_int_regslice),
    .storemerge4_i49_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i49_i_i_out),
    .storemerge4_i49_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i49_i_i_out_ap_vld),
    .storemerge4_i47_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i47_i_i_out),
    .storemerge4_i47_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i47_i_i_out_ap_vld),
    .storemerge4_i45_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i45_i_i_out),
    .storemerge4_i45_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i45_i_i_out_ap_vld),
    .storemerge4_i43_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i43_i_i_out),
    .storemerge4_i43_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i43_i_i_out_ap_vld),
    .storemerge4_i41_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i41_i_i_out),
    .storemerge4_i41_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i41_i_i_out_ap_vld),
    .storemerge4_i39_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i39_i_i_out),
    .storemerge4_i39_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i39_i_i_out_ap_vld),
    .storemerge4_i37_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i37_i_i_out),
    .storemerge4_i37_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i37_i_i_out_ap_vld),
    .storemerge4_i35_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i35_i_i_out),
    .storemerge4_i35_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i35_i_i_out_ap_vld),
    .storemerge4_i33_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i33_i_i_out),
    .storemerge4_i33_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i33_i_i_out_ap_vld),
    .storemerge4_i31_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i31_i_i_out),
    .storemerge4_i31_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i31_i_i_out_ap_vld),
    .storemerge4_i29_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i29_i_i_out),
    .storemerge4_i29_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i29_i_i_out_ap_vld),
    .storemerge4_i27_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i27_i_i_out),
    .storemerge4_i27_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i27_i_i_out_ap_vld),
    .storemerge4_i25_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i25_i_i_out),
    .storemerge4_i25_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i25_i_i_out_ap_vld),
    .storemerge4_i23_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i23_i_i_out),
    .storemerge4_i23_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i23_i_i_out_ap_vld),
    .storemerge4_i21_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i21_i_i_out),
    .storemerge4_i21_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i21_i_i_out_ap_vld),
    .storemerge4_i19_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i19_i_i_out),
    .storemerge4_i19_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i19_i_i_out_ap_vld),
    .storemerge4_i17_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i17_i_i_out),
    .storemerge4_i17_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i17_i_i_out_ap_vld),
    .storemerge4_i15_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i15_i_i_out),
    .storemerge4_i15_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i15_i_i_out_ap_vld),
    .storemerge4_i13_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i13_i_i_out),
    .storemerge4_i13_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i13_i_i_out_ap_vld),
    .storemerge4_i11_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i11_i_i_out),
    .storemerge4_i11_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i11_i_i_out_ap_vld),
    .storemerge4_i9_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i9_i_i_out),
    .storemerge4_i9_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i9_i_i_out_ap_vld),
    .storemerge4_i7_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i7_i_i_out),
    .storemerge4_i7_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i7_i_i_out_ap_vld),
    .storemerge4_i5_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i5_i_i_out),
    .storemerge4_i5_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i5_i_i_out_ap_vld),
    .storemerge4_i3_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i3_i_i_out),
    .storemerge4_i3_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i3_i_i_out_ap_vld),
    .storemerge4_i1_i_i_out(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i1_i_i_out),
    .storemerge4_i1_i_i_out_ap_vld(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i1_i_i_out_ap_vld)
);

my_prj_accelerator_myproject grp_myproject_fu_237(
    .input_layer_0_val1(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i47_i_i_out),
    .input_layer_1_val2(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i45_i_i_out),
    .input_layer_2_val3(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i43_i_i_out),
    .input_layer_3_val4(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i41_i_i_out),
    .input_layer_4_val5(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i39_i_i_out),
    .input_layer_5_val6(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i37_i_i_out),
    .input_layer_6_val7(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i35_i_i_out),
    .input_layer_7_val8(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i33_i_i_out),
    .input_layer_8_val9(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i31_i_i_out),
    .input_layer_9_val10(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i29_i_i_out),
    .input_layer_10_val11(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i27_i_i_out),
    .input_layer_11_val12(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i25_i_i_out),
    .input_layer_12_val13(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i23_i_i_out),
    .input_layer_13_val14(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i21_i_i_out),
    .input_layer_14_val15(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i19_i_i_out),
    .input_layer_15_val16(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i17_i_i_out),
    .input_layer_16_val17(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i15_i_i_out),
    .input_layer_17_val18(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i13_i_i_out),
    .input_layer_18_val19(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i11_i_i_out),
    .input_layer_19_val20(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i9_i_i_out),
    .input_layer_20_val21(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i7_i_i_out),
    .input_layer_21_val22(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i5_i_i_out),
    .input_layer_22_val23(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i3_i_i_out),
    .input_layer_23_val24(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i1_i_i_out),
    .input_layer_24_val25(grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_storemerge4_i49_i_i_out),
    .layer9_out(grp_myproject_fu_237_layer9_out),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .input_layer_0_val1_ap_vld(1'b1),
    .input_layer_1_val2_ap_vld(1'b1),
    .input_layer_2_val3_ap_vld(1'b1),
    .input_layer_3_val4_ap_vld(1'b1),
    .input_layer_4_val5_ap_vld(1'b1),
    .input_layer_5_val6_ap_vld(1'b1),
    .input_layer_6_val7_ap_vld(1'b1),
    .input_layer_7_val8_ap_vld(1'b1),
    .input_layer_8_val9_ap_vld(1'b1),
    .input_layer_9_val10_ap_vld(1'b1),
    .input_layer_10_val11_ap_vld(1'b1),
    .input_layer_11_val12_ap_vld(1'b1),
    .input_layer_12_val13_ap_vld(1'b1),
    .input_layer_13_val14_ap_vld(1'b1),
    .input_layer_14_val15_ap_vld(1'b1),
    .input_layer_15_val16_ap_vld(1'b1),
    .input_layer_16_val17_ap_vld(1'b1),
    .input_layer_17_val18_ap_vld(1'b1),
    .input_layer_18_val19_ap_vld(1'b1),
    .input_layer_19_val20_ap_vld(1'b1),
    .input_layer_20_val21_ap_vld(1'b1),
    .input_layer_21_val22_ap_vld(1'b1),
    .input_layer_22_val23_ap_vld(1'b1),
    .input_layer_23_val24_ap_vld(1'b1),
    .input_layer_24_val25_ap_vld(1'b1),
    .ap_start(grp_myproject_fu_237_ap_start),
    .layer9_out_ap_vld(grp_myproject_fu_237_layer9_out_ap_vld),
    .ap_done(grp_myproject_fu_237_ap_done),
    .ap_ready(grp_myproject_fu_237_ap_ready),
    .ap_idle(grp_myproject_fu_237_ap_idle),
    .ap_continue(grp_myproject_fu_237_ap_continue)
);

my_prj_accelerator_copy_output grp_copy_output_fu_273(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_copy_output_fu_273_ap_start),
    .ap_done(grp_copy_output_fu_273_ap_done),
    .ap_idle(grp_copy_output_fu_273_ap_idle),
    .ap_ready(grp_copy_output_fu_273_ap_ready),
    .result_TREADY(grp_copy_output_fu_273_result_TREADY),
    .result_TDATA(grp_copy_output_fu_273_result_TDATA),
    .result_TVALID(grp_copy_output_fu_273_result_TVALID),
    .result_TKEEP(grp_copy_output_fu_273_result_TKEEP),
    .result_TSTRB(grp_copy_output_fu_273_result_TSTRB),
    .result_TLAST(grp_copy_output_fu_273_result_TLAST),
    .score_int_val(result_int_fu_184),
    .last(icmp_ln104_reg_622),
    .result_TDATA_blk_n(grp_copy_output_fu_273_result_TDATA_blk_n)
);

my_prj_accelerator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_x_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(x_TDATA),
    .vld_in(x_TVALID),
    .ack_in(regslice_both_x_V_data_V_U_ack_in),
    .data_out(x_TDATA_int_regslice),
    .vld_out(x_TVALID_int_regslice),
    .ack_out(x_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_V_data_V_U_apdone_blk)
);

my_prj_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_x_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(x_TKEEP),
    .vld_in(x_TVALID),
    .ack_in(regslice_both_x_V_keep_V_U_ack_in),
    .data_out(x_TKEEP_int_regslice),
    .vld_out(regslice_both_x_V_keep_V_U_vld_out),
    .ack_out(x_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_V_keep_V_U_apdone_blk)
);

my_prj_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_x_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(x_TSTRB),
    .vld_in(x_TVALID),
    .ack_in(regslice_both_x_V_strb_V_U_ack_in),
    .data_out(x_TSTRB_int_regslice),
    .vld_out(regslice_both_x_V_strb_V_U_vld_out),
    .ack_out(x_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_V_strb_V_U_apdone_blk)
);

my_prj_accelerator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_x_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(x_TLAST),
    .vld_in(x_TVALID),
    .ack_in(regslice_both_x_V_last_V_U_ack_in),
    .data_out(x_TLAST_int_regslice),
    .vld_out(regslice_both_x_V_last_V_U_vld_out),
    .ack_out(x_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_V_last_V_U_apdone_blk)
);

my_prj_accelerator_regslice_both #(
    .DataWidth( 32 ))
regslice_both_result_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(result_TDATA_int_regslice),
    .vld_in(grp_copy_output_fu_273_result_TVALID),
    .ack_in(result_TREADY_int_regslice),
    .data_out(result_TDATA),
    .vld_out(regslice_both_result_V_data_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_data_V_U_apdone_blk)
);

my_prj_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_result_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(result_TKEEP_int_regslice),
    .vld_in(grp_copy_output_fu_273_result_TVALID),
    .ack_in(regslice_both_result_V_keep_V_U_ack_in_dummy),
    .data_out(result_TKEEP),
    .vld_out(regslice_both_result_V_keep_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_keep_V_U_apdone_blk)
);

my_prj_accelerator_regslice_both #(
    .DataWidth( 4 ))
regslice_both_result_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(result_TSTRB_int_regslice),
    .vld_in(grp_copy_output_fu_273_result_TVALID),
    .ack_in(regslice_both_result_V_strb_V_U_ack_in_dummy),
    .data_out(result_TSTRB),
    .vld_out(regslice_both_result_V_strb_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_strb_V_U_apdone_blk)
);

my_prj_accelerator_regslice_both #(
    .DataWidth( 1 ))
regslice_both_result_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(result_TLAST_int_regslice),
    .vld_in(grp_copy_output_fu_273_result_TVALID),
    .ack_in(regslice_both_result_V_last_V_U_ack_in_dummy),
    .data_out(result_TLAST),
    .vld_out(regslice_both_result_V_last_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((regslice_both_result_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_myproject_fu_237_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_sync_reg_grp_myproject_fu_237_ap_done <= 1'b0;
        end else if ((grp_myproject_fu_237_ap_done == 1'b1)) begin
            ap_sync_reg_grp_myproject_fu_237_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_myproject_fu_237_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_sync_reg_grp_myproject_fu_237_ap_ready <= 1'b0;
        end else if ((grp_myproject_fu_237_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_myproject_fu_237_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln95_fu_299_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_ready == 1'b1)) begin
            grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_copy_output_fu_273_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state6) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_copy_output_fu_273_ap_start_reg <= 1'b1;
        end else if ((grp_copy_output_fu_273_ap_ready == 1'b1)) begin
            grp_copy_output_fu_273_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_myproject_fu_237_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) | ((ap_sync_grp_myproject_fu_237_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state5)))) begin
            grp_myproject_fu_237_ap_start_reg <= 1'b1;
        end else if ((grp_myproject_fu_237_ap_ready == 1'b1)) begin
            grp_myproject_fu_237_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        n_fu_80 <= 31'd0;
    end else if (((icmp_ln95_fu_299_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        n_fu_80 <= n_2_fu_304_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        N_read_reg_608 <= N_dout;
        p_read_67_reg_453 <= p_read;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln104_reg_622 <= icmp_ln104_fu_310_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_copy_output_fu_273_result_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        result_TDATA_reg <= grp_copy_output_fu_273_result_TDATA;
        result_TKEEP_reg <= grp_copy_output_fu_273_result_TKEEP;
        result_TLAST_reg <= grp_copy_output_fu_273_result_TLAST;
        result_TSTRB_reg <= grp_copy_output_fu_273_result_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_myproject_fu_237_layer9_out_ap_vld == 1'b1))) begin
        result_int_fu_184 <= grp_myproject_fu_237_layer9_out;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        N_blk_n = N_empty_n;
    end else begin
        N_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        N_read = 1'b1;
    end else begin
        N_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_copy_output_fu_273_result_TDATA_blk_n == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((regslice_both_result_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_result_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_result_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
        grp_myproject_fu_237_ap_continue = 1'b1;
    end else begin
        grp_myproject_fu_237_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        result_TDATA_blk_n = grp_copy_output_fu_273_result_TDATA_blk_n;
    end else begin
        result_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((grp_copy_output_fu_273_result_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        result_TDATA_int_regslice = grp_copy_output_fu_273_result_TDATA;
    end else begin
        result_TDATA_int_regslice = result_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_copy_output_fu_273_result_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        result_TKEEP_int_regslice = grp_copy_output_fu_273_result_TKEEP;
    end else begin
        result_TKEEP_int_regslice = result_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_copy_output_fu_273_result_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        result_TLAST_int_regslice = grp_copy_output_fu_273_result_TLAST;
    end else begin
        result_TLAST_int_regslice = result_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_copy_output_fu_273_result_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        result_TSTRB_int_regslice = grp_copy_output_fu_273_result_TSTRB;
    end else begin
        result_TSTRB_int_regslice = result_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_TREADY_int_regslice = grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_x_TREADY;
    end else begin
        x_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln95_fu_299_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_copy_output_fu_273_result_TDATA_blk_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state8 : begin
            if (((regslice_both_result_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_NS_fsm_state6 = ap_NS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((1'b0 == N_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state5_on_subcall_done = ((ap_sync_reg_grp_myproject_fu_237_ap_ready & ap_sync_reg_grp_myproject_fu_237_ap_done) == 1'b0);
end

assign ap_sync_grp_myproject_fu_237_ap_ready = (grp_myproject_fu_237_ap_ready | ap_sync_reg_grp_myproject_fu_237_ap_ready);

assign grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start = grp_Loop_VITIS_LOOP_95_1_proc_Pipeline_VITIS_LOOP_9_1_fu_200_ap_start_reg;

assign grp_copy_output_fu_273_ap_start = grp_copy_output_fu_273_ap_start_reg;

assign grp_copy_output_fu_273_result_TREADY = (result_TREADY_int_regslice & ap_CS_fsm_state6);

assign grp_myproject_fu_237_ap_start = grp_myproject_fu_237_ap_start_reg;

assign icmp_ln104_fu_310_p2 = ((zext_ln95_fu_295_p1 == p_read_67_reg_453) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_299_p2 = (($signed(zext_ln95_fu_295_p1) < $signed(N_read_reg_608)) ? 1'b1 : 1'b0);

assign n_2_fu_304_p2 = (n_fu_80 + 31'd1);

assign result_TVALID = regslice_both_result_V_data_V_U_vld_out;

assign result_TVALID_int_regslice = grp_copy_output_fu_273_result_TVALID;

assign x_TREADY = regslice_both_x_V_data_V_U_ack_in;

assign zext_ln95_fu_295_p1 = n_fu_80;

endmodule //my_prj_accelerator_Loop_VITIS_LOOP_95_1_proc
